# Site settings
title:T_I_M_V_F_B_S 
email:ahn.assari@gmail.com 
description: This is Tj Ahns blog 
 # Write an awesome description for your new site here. You can edit this
 # line in _config.yml. It will appear in your document head meta (for
 # Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nothing 
github_username: assariTJahn 
<<<<<<< HEAD
=======
source:/blog/
>>>>>>> 6b154b01241831ee5f9bfb73605f2b502ce934fd
# Build settings
markdown: kramdown
